apiVersion: v1
kind: Service
metadata:
  name: myintro-service
spec:
  type: NodePort
  selector:
    app: myintro
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30001   # Port on your node
